### ISSUE TITLE
Compatibility version went backwards

### ISSUE THREAD

**Issue by jmroot** [mdadams/jasper#107]
On macOS, JasPer 1.900.29 installed a libjasper.4.dylib with a compatibility version of 5.0.0. But with JasPer 2.0.6, the same library has compatibility version 4.0.0. This means that binaries built against the older version will not run with the newer version, because it appears to be older.

I'm not sure if there is a good solution to this, as cmake appears to tie the library major version (i.e. the 4 in libjasper.4.dylib) to the compatibility version, setting both from the SOVERSION property.

https://cmake.org/cmake/help/v3.7/prop_tgt/SOVERSION.html

**Comment by mdadams** [comment]
@jmroot Could this be a bug in your version of CMake?  It appears that some versions of CMake have a bug on OSX related to library versioning information.  For example, see:
    https://cmake.org/Bug/view.php?id=14140
When I build JasPer for OSX for the most recent commit on the master branch using Travis CI, the build uses the following flags when producing the library: -compatibility_version 4.0.0 -current_version 4.0.0.
Please see the following output from Travis CI:
    https://s3.amazonaws.com/archive.travis-ci.org/jobs/186097091/log.txt
(Search for "compatibility_version".)
As far as I can tell, the linker is being told to use the JasPer ABI version 4 (not 5).
What version of CMake are you using?  And what is being specified for the -compatibility_version and the -current_version flags when you build?

**Comment by jmroot** [comment]
Cmake 3.7.1. However the problem is not exactly that 4.0.0 is used now, it's that 5.0.0 was used previously (by the old autotools-based build). The current version must never go down; it must always be greater than or equal to the compatibility version, which must itself go up whenever new symbols are added.

It's completely valid to have a libjasper.4.dylib with current and compatibility versions that bear no relationship to the number 4 at all. It's only cmake that doesn't allow that.

Apple's documentation on library versioning: https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html#//apple_ref/doc/uid/TP40002013-SW23

**Comment by mdadams** [comment]
@jmroot If I am understanding correctly, there is no bug in the current version of JasPer then, as far as shared libraries are concerned.  The real problem is that the old autotools-based build was assigning an incorrect ABI version number to the JasPer shared library that was built on OSX.  Is my understanding correct?  No other users of JasPer have complained about a backward jump in library versioning.  So, I have to assume that only the OSX platform is affected by this issue.  What is the largest ABI version that was used by JasPer in the past on OSX?  Is this value 5?  The best solution that I can think of (assuming that 5 is the largest value used in the past for OSX) is the following:

    1) Change JasPer now as follows: On OSX only, use JAS_SO_VERSION + 2 (4+2=6) as the value for SOVERSION instead of JAS_SO_VERSION (4).  This will avoid overlap in ABI version numbering on OSX.

    2) In the future, when I next bump JAS_SO_VERSION for all library users, I will bump it by 3 (instead of 1) and remove the hack in item 1 above.  At this point, all platforms would again be using the same ABI version (7).

Does this sound like a workable solution to you?

I do not want to change the ABI version number for everyone until an ABI breaking change is actually made, however, because doing so will negatively impact all Linux distributions (and probably other library users as well).  In particular, changing the ABI version number will, in practice, prevent Linux distributions from picking up bug fixes from upstream.

**Comment by jmroot** [comment]
Yes, changing the major version would not solve anything, as that would require dependents to be rebuilt, which is what we're trying to avoid. The right solution would be to set current_version and compatibility_version to 5, but leave the major version unchanged. The problem, as I mentioned earlier, is that cmake doesn't appear to provide any way to do that.

Also, I found out why this happened at least. This is the command run by the build of 1.900.29:
```sh
/bin/sh ../../libtool  --tag=CC   --mode=link clang  -Os -arch x86_64 -I/opt/local/include -std=c11 -pedantic -Wall -Wno-unused -version-info 4:0:0 -L/opt/local/lib -o libjasper.la -rpath /usr/local/lib dummy.lo base/libbase.la bmp/libbmp.la jp2/libjp2.la jpc/libjpc.la jpg/libjpg.la mif/libmif.la pgx/libpgx.la pnm/libpnm.la ras/libras.la -lm  -ljpeg
libtool: link: clang -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libjasper.4.dylib  .libs/dummy.o   -Wl,-force_load,base/.libs/libbase.a -Wl,-force_load,bmp/.libs/libbmp.a -Wl,-force_load,jp2/.libs/libjp2.a -Wl,-force_load,jpc/.libs/libjpc.a -Wl,-force_load,jpg/.libs/libjpg.a -Wl,-force_load,mif/.libs/libmif.a -Wl,-force_load,pgx/.libs/libpgx.a -Wl,-force_load,pnm/.libs/libpnm.a -Wl,-force_load,ras/.libs/libras.a  -L/opt/local/lib -lm -ljpeg  -Os -arch x86_64   -install_name  /usr/local/lib/libjasper.4.dylib -compatibility_version 5 -current_version 5.0 -Wl,-single_module
```

Notice that `-version-info 4:0:0` results in `-o .libs/libjasper.4.dylib` but then `-compatibility_version 5 -current_version 5.0`. The reason for that is in this snippet from jasper-1.900.29/ac_aux/ltmain.sh:7398:
```sh
	darwin)
	  # Like Linux, but with the current version available in
	  # verstring for coding it into the library header
	  func_arith $current - $age
	  major=.$func_arith_result
	  versuffix="$major.$age.$revision"
	  # Darwin ld doesn't like 0 for these options...
	  func_arith $current + 1
	  minor_current=$func_arith_result
	  xlcverstring="${wl}-compatibility_version ${wl}$minor_current ${wl}-current_version ${wl}$minor_current.$revision"
	  verstring="-compatibility_version $minor_current -current_version $minor_current.$revision"
	  ;;
```
As you can see, it adds 1 to current to produce minor_current. This is presumably because the documented way to use libtool is to start your version-info at 0:0:0, but 0 is not a valid value for current_version or compatibility_version. So there you have it.

**Comment by mdadams** [comment]
@jmroot I don't know if I misunderstood your response, but wouldn't the solution that I proposed above solve the problem?  In other words, won't the following solve the problem nicely for everyone?

1) Change the current version of JasPer as follows: On OSX only, use JAS_SO_VERSION + 2 (4+2=6) as the value for SOVERSION instead of JAS_SO_VERSION (4).  This will avoid overlap in ABI version numbering on OSX.

2) In the future, when I next bump JAS_SO_VERSION for all library users, I will bump it by 3 (instead of 1) and remove the hack in item 1 above.  At this point, all platforms would again be using the same ABI version (7).

I realize that the above solution that I am proposing will not make cmake number things the same way as autotools.  But using the exact same numbering scheme is not the only way to fix the problem.  Any approach that prevents the overlapping ABI version numbering would solve the problem.

I am sorry if I am missing something obvious, but I am not a shared library guru.

**Comment by jmroot** [comment]
Changing SOVERSION will definitely not help. What you suggest does make sense though, if you change VERSION instead. I just did a proof-of-concept build like this:
```
set(JAS_SO_VERSION 4)
set(JAS_SO_MINOR 0)
set(JAS_SO_RELEASE 0)
set(JAS_SO_NAME "5.${JAS_SO_MINOR}.${JAS_SO_RELEASE}")
```
and this was the result:
```
% ls -l work/destroot/opt/local/lib/
total 512
lrwxr-xr-x  1 root  admin      21 29 Dec 21:35 libjasper.4.dylib -> libjasper.5.0.0.dylib
-rwxr-xr-x+ 1 root  admin  250152 29 Dec 21:35 libjasper.5.0.0.dylib
lrwxr-xr-x  1 root  admin      17 29 Dec 21:35 libjasper.dylib -> libjasper.4.dylib
% otool -L work/destroot/opt/local/lib/libjasper.5.0.0.dylib 
work/destroot/opt/local/lib/libjasper.5.0.0.dylib:
	/opt/local/lib/libjasper.4.dylib (compatibility version 4.0.0, current version 5.0.0)
	/opt/local/lib/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
Slightly odd perhaps, but valid, and it solves the problem.

So, I would suggest changing JAS_SO_NAME to 5.0.0 for OS X only, leaving it at 4.0.0 for other platforms. Then next time the ABI changes, remove the special case for OS X and set it to 6.0.0 for all platforms.

**Comment by mdadams** [comment]
@jmroot I am not sure that I correctly understand the problem, but I have adopted your proposed change as a fix.  The change is in commit f8555af8c2b0a13182e5e0e6339f967413544481. The fix seems to work correctly on Travis CI.  See:
    https://travis-ci.org/mdadams/jasper/jobs/187697818
    and
   https://travis-ci.org/mdadams/jasper/jobs/187697817
I am closing this issue on the assumption that the problem is now resolved.  If this is not the case, please let me know, and I will re-open.

**Comment by jmroot** [comment]
Thanks, that commit looks good.
