### ISSUE TITLE
cmake can find mismatched OpenGL and GLUT

### ISSUE THREAD

**Issue by jmroot** [mdadams/jasper#108]
On macOS you can either use the native OpenGL and GLUT frameworks, or glx with mesa and freeglut. You can't mix and match. But if freeglut is installed on the system, JasPer's build system will find OpenGL.framework for OPENGL_LIBRARIES, but then find freeglut's libglut.dylib for GLUT_LIBRARIES.

This may be a bug in cmake's FindGLUT module.

**Comment by mdadams** [comment]
@jmroot I don't have a good solution to this problem.  In the scenario that you describe, essentially, the user has chosen to install libraries that are incompatible with ones provided by their OS vendor (namely, Apple).  If a user does something like this, they should expect at least some problems.  The ideal solution would probably be to have CMake modify the FindOpenGL and FindGLUT modules so that one can disable/enable various flavors of libraries.  The difficulty is that this must work across all platforms and not just on MacOSX.   So, practically speaking, the ideal solution may not be workable.  My inclination is to simply say that JasPer only officially supports the use of Apple's OpenGL and GLUT frameworks.  If you have a simple workaround (e.g., using some -D options to cmake) to allow the non-Apple FreeGLUT library to be used, I could document this in the JasPer manual.  That's about the best that I can do, in the absence of any better solutions from others.  Unless you have any better suggestions, I am going to mark this issue closed.

**Comment by jmroot** [comment]
It would be fine to disallow the use of freeglut/mesa on macOS, the issue is just that cmake by default decides to use the native framework for OpenGL but not for GLUT. MacPorts has worked around it by passing `-DGLUT_glut_LIBRARY=/System/Library/Frameworks/GLUT.framework` to cmake.

**Comment by mdadams** [comment]
Since only supporting the native framework on OSX is acceptable to you, I am going to close this issue.  In order to address your concern that a user might have Freeglut installed, I have also amended the JasPer installation instructions in the INSTALL file in commit 74f7ac288a771cb0856f70dd4743b9ed5e797a16 in order to mention your workaround for users with Freeglut installed.  In particular, I added a comment for OSX as given below.  Let me know if it needs any technical corrections/clarifications.

When building the JasPer software under Mac OSX, only the use of the
native framework for OpenGL is officially supported.  If the Freeglut
library is installed on your system, you will need to ensure that the
native GLUT library (as opposed to the Freeglut library) is used by the
build process.  This can be accomplished by adding an extra option to
the cmake command line that resembles the following:

    -DGLUT_glut_LIBRARY=/System/Library/Frameworks/GLUT.framework
