### ISSUE TITLE
any hope of a standard build system?

### ISSUE THREAD

**Issue by edhartnett** [mdadams/jasper#195]
I am involved in a lot of scientific software installs, and jasper is required for some libraries.

Unlike almost all the other libraries I deal with, jasper does not provide a standard build system based on autoconf/automake. While I understand that cmake has its fans, it's not what is used in HPC and many other science applications.

Is there any plan to create an autotools build system for jasper? I would be very helpful.

**Comment by mdadams** [comment]
There are good technical reasons why JasPer moved from Autotools to CMake.  Most importantly, CMake has much better cross-platform support.  Autotools is great if you only care about UNIX-like OSes.  JasPer has users on many OSes, however. For this reason, I strongly believe that many people would disagree with your implied suggestion that CMake is not a standard build system.  In any case, CMake is easy to install.  You can download pre-built CMake binaries for many platforms from http://www.cmake.org.

**Comment by edhartnett** [comment]
I question the wisdom of moving from the standard build system to a non-standard one, just to support Windows. (Not sure what other OSs you refer to, there's pretty much Windows and Linux now.)

Generally, projects I work on have both autotools and cmake build, with the cmake build being there to support windows and autotools to support unix. You might consider this.

Jasper is used by a bunch of weather models and climate code, and that code is never on windows. Nor do many of the associated packages use cmake, but all use autotools. Using cmake for jasper and autotools for everything else in the stack is pretty annoying. So I really would like an autotools build of jasper.

Fortunately there is at least one version of jasper out there which has an autotools build, and I have learned that this is what science programming packages like NCL recommend: http://www.ijg.org/files/jpegsr9b.zip. Not sure if this is a down-rev version or what, but it works for now. 

If this is an old version, be advised that many users are apparently still using it due to the build system.

If I get time I will fork this project a put together a standard build system for the use of science packages. I would be happy to offer that build system as a PR, but perhaps that won't be of interest. In that case my fork will allow science users to get an autotools build of jasper.

**Comment by mdadams** [comment]
First, the Zip file that you mention appears to be for the IJG software, which is essentially a JPEG codec, not a JPEG-2000 codec.  Second, there are more OSes out there than simply Windows and Linux. For example, MacOS is an extremely popular OS and while MacOS is a Unix variant, it is not Linux.  Third, CMake can generate the project files used by IDEs such as XCode on MacOS and Visual Studio on Windows.   As far as I know, Autotools cannot generate such project files, but CMake can.  This was definitely the case when JasPer switched from Autotools to CMake, and to the best of my knowledge, this is still the case now.  Lastly, since you seem to be using Linux, I would like to note that all major Linux distributions have packages for CMake (which can easily be installed using the appropriate Linux package manager).  So, my advice would be to simply install CMake using your Linux package manager and then follow the build instructions for JasPer using CMake.  I don't plan to provide Autotools support for JasPer, since CMake can be used on all platforms for which Autotools is a viable option and CMake can be used in many additional cases where Autotools is not viable.

**Comment by wanghan0501** [comment]
could you release a pre-compiled library on vs2013? It's to hard to compile on windows platform...
