### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [mdadams/jasper#205]
I think that it would be good to make new release :)

**Comment by mdadams** [comment]
https://github.com/mdadams/jasper/releases/tag/version-2.0.16 already includes the most recent commit.

**Comment by kloczek** [comment]
One CVS  looks like still is not in released 2.0.16 code https://src.fedoraproject.org/rpms/jasper/tree/master

**Comment by mdadams** [comment]
I just looked at the following patch file, and as best I can tell, this patch has already been applied:
https://src.fedoraproject.org/rpms/jasper/raw/master/f/jasper-2.0.14-CVE-2016-9396.patch
The name of this patch file suggests that it was made against JasPer 2.0.14, not 2.0.16.  Perhaps, you were looking at the wrong JasPer version, when you concluded that the patch had not been applied?  In any case, as best I can tell, this issue is already solved.  If I have misunderstood your comments, please clarify and I can reopen the issue if needed.

**Comment by jubalh** [comment]
CVE-2016-9396 was fixed in https://github.com/mdadams/jasper/commit/a10536d5f7f3164b0a1f1ae3e533f4a12ca6f543 so all should be fine.
