### ISSUE TITLE
jas_malloc.c uses C11 feature max_align_t

### ISSUE THREAD

**Issue by SoapGentoo** [mdadams/jasper#66]
In Gentoo we require setting C11 support, otherwise compilers error out in `jas_malloc.c` due to the `max_align_t` typedef. I recommend either using gnulib + max_align_t, or just assuming the largest type is 16 or even 32 bytes in order to be able to use just C99 features.

https://bugs.gentoo.org/show_bug.cgi?id=598418

**Comment by mdadams** [comment]
I am planning to start relying on more C11 features in the future.  So, I have enabled C11 support in configure.ac in a manner that should work for GCC and Clang.  I want to make the memory allocator thread safe, which requires mutexes and/or atomics, both C11 features.  In the Gentoo world, do you foresee any big problems that would be caused by requiring C11 support for JasPer, as long as the configure script for JasPer enables C11 for the compiler? (See commit 4f0e63ea0d5ab4b8b384625e4a978f09c7e94a4c for the configure.ac changes.)

**Comment by SoapGentoo** [comment]
@mdadams sure, but given the previous PR for the format flags, it sounded more like you wanted to restrict yourself only to features available in C99. Requesting C11 is just as good for us.
