### ISSUE TITLE
Heap Buffer Overflow (READ of size 4) in jpc_pi_nextrpcl()

### ISSUE THREAD

**Issue by VERTCraig** [mdadams/jasper#73]
Fuzzing the imginfo example tool with AFL, I came across a test case that triggers a heap buffer overflow.

The ASAN report is as follows:
=================================================================
==14266==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000e090 at pc 0x7fee9630e0f2 bp 0x7ffd4a9ae990 sp 0x7ffd4a9ae988
READ of size 4 at 0x60200000e090 thread T0
    #0 0x7fee9630e0f1 in jpc_pi_nextrpcl /home/spotless/jasper/jasper/src/libjasper/jpc/jpc_t2cod.c:301:25
    #1 0x7fee9630e0f1 in jpc_pi_next /home/spotless/jasper/jasper/src/libjasper/jpc/jpc_t2cod.c:119
    #2 0x7fee963112b5 in jpc_dec_decodepkts /home/spotless/jasper/jasper/src/libjasper/jpc/jpc_t2dec.c:441:14
    #3 0x7fee96275dbe in jpc_dec_process_sod /home/spotless/jasper/jasper/src/libjasper/jpc/jpc_dec.c:594:6
    #4 0x7fee9627e1e0 in jpc_dec_decode /home/spotless/jasper/jasper/src/libjasper/jpc/jpc_dec.c:391:12
    #5 0x7fee9627e1e0 in jpc_decode /home/spotless/jasper/jasper/src/libjasper/jpc/jpc_dec.c:255
    #6 0x7fee9624d6aa in jp2_decode /home/spotless/jasper/jasper/src/libjasper/jp2/jp2_dec.c:215:21
    #7 0x7fee961dbe49 in jas_image_decode /home/spotless/jasper/jasper/src/libjasper/base/jas_image.c:396:18
    #8 0x4dc375 in main /home/spotless/jasper/jasper/src/appl/imginfo.c:203:16
    #9 0x7fee94f66a3f in __libc_start_main /build/buildd/glibc-2.21/csu/libc-start.c:289
    #10 0x435728 in _start (/home/spotless/jasper/jasper/src/appl/.libs/lt-imginfo+0x435728)

AddressSanitizer can not describe address in more detail (wild memory access suspected).
SUMMARY: AddressSanitizer: heap-buffer-overflow /home/spotless/jasper/jasper/src/libjasper/jpc/jpc_t2cod.c:301 jpc_pi_nextrpcl
Shadow bytes around the buggy address:
  0x0c047fff9bc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9bd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9be0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9bf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9c00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fff9c10: fa fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9c20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9c30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9c40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9c50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9c60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==14266==ABORTING

Here is the base64 encoded test case:
AAAADGpQICANCocKAAAAFGZ0eXBqcDIgAAAAAGpwMiAAAAAtanAyaAAAABZpaGRyAAAAIAAAACAA
AwcHAAAAAAAPY29scgIAAAAAABAAAADYanAyY/9P/1EALwAAAAAAIAAAACAAAAAAAAAAAAAAACAA
AAAgAAAAAAAAABMAAwcBAwcB/vj+/v9SAAwAAgABAQsEBAAA/1wABEBA/1wAJQABQ3JlYXRlZCBi
eSBPcGVuSlBFRyB2ZXJzaW9uIDIuMS4w/5AACgAAAAAAYAAB/5Pc1wAYgA4hv/wu6rI3ztvzBVI/
Qy0r3ddkxD1n/3KrNSv4Q8qzX8rZJIW0WVyNJf134Mt4HYdg1vgobo9lRSXq/12/GnETEKne5N1r
Qfc43GZP/9k=

**Comment by mdadams** [comment]
I cannot reproduce this problem on my machine with either GCC 6.1.0 or Clang 3.8.1 with ASAN enabled.  This problem might possibly have the same root cause as the problem in #75.  If this is the case, the problem should be fixed now. (See commit 1f0dfe5a42911b6880a1445f13f6d615ddb55387.) Is the problem fixed now on the master branch? If the problem is not fixed, there is nothing I can do unless you can provide additional information.  It is not uncommon for bugs like this (and many other bugs as well) to be caused by overflow.  If this is the case, running your failed test case with the undefined-behavior sanitizer enabled can often be very useful, as this can sometimes point directly to the source of the bug (i.e., an overflow that later causes the code to go off the deep end).

For now, I am going to mark this issue closed.  If the problem is not resolved and you can provide further information to help me locate the source of the problem, I can re-open this issue.

**Comment by VERTCraig** [comment]
The bug was resolved.  Thanks
