### ISSUE TITLE
jpg_mkimage failed

### ISSUE THREAD

**Issue by ilovezfs** [mdadams/jasper#77]
I'm seeing a regression from https://github.com/mdadams/jasper/commit/3afacc174867cc9d1f74ef2683bc780de4b0b2df

```
$ jasper --input /usr/local/Homebrew/Library/Homebrew/test/fixtures/test.jpg --output test.bmp
jpg_mkimage failed
error: cannot load image data
```

The error is coming from
```
+		if (cinfo->image_width < JAS_IMAGE_COORD_MIN ||
+		  cinfo->image_width > JAS_IMAGE_COORD_MAX ||
+		  cinfo->image_height < JAS_IMAGE_COORD_MIN ||
+		  cinfo->image_height > JAS_IMAGE_COORD_MAX) {
+			goto error;
+		}
```

Printing
```
printf("cinfo->image_width < JAS_IMAGE_COORD_MIN : %d\n", cinfo->image_width < JAS_IMAGE_COORD_MIN);
printf("cinfo->image_width > JAS_IMAGE_COORD_MAX : %d\n", cinfo->image_width > JAS_IMAGE_COORD_MAX);
printf("cinfo->image_height < JAS_IMAGE_COORD_MIN : %d\n", cinfo->image_height < JAS_IMAGE_COORD_MIN);
printf("cinfo->image_height > JAS_IMAGE_COORD_MAX : %d\n", cinfo->image_height > JAS_IMAGE_COORD_MAX);
printf("cinfo->image_width: %p\n", cinfo->image_width);
printf("JAS_IMAGE_COORD_MIN: %p\n", JAS_IMAGE_COORD_MIN);
printf("JAS_IMAGE_COORD_MAX: %p\n", JAS_IMAGE_COORD_MAX);
printf("cinfo->image_height: %p\n", cinfo->image_height);
printf("ruh roh\n");
```
I get
```
$ /usr/local/Cellar/jasper/HEAD-5fffc50/bin/jasper --input /usr/local/Homebrew/Library/Homebrew/test/fixtures/test.jpg --output test.bmp
cinfo->image_width < JAS_IMAGE_COORD_MIN : 1
cinfo->image_width > JAS_IMAGE_COORD_MAX : 0
cinfo->image_height < JAS_IMAGE_COORD_MIN : 1
cinfo->image_height > JAS_IMAGE_COORD_MAX : 0
cinfo->image_width: 0x1
JAS_IMAGE_COORD_MIN: 0x80000000
JAS_IMAGE_COORD_MAX: 0x7fffffff
cinfo->image_height: 0x1
ruh roh
jpg_mkimage failed
error: cannot load image data
```

**Comment by ilovezfs** [comment]
The test image is here

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/fixtures/test.jpg

https://raw.githubusercontent.com/Homebrew/brew/master/Library/Homebrew/test/fixtures/test.jpg

**Comment by mdadams** [comment]
I cannot reproduce the problem on my machine, but I think that I can tell what is wrong from the information that you provided.  The test against the JAS_IMAGE_COORD_MIN value should not be in the code in question since JDIMENSION is (I think) always an unsigned type.  It looks like you are on a machine where int_fast32_t and JDIMENSION are both 32-bit integers (where the latter is presumably unsigned).  On such a machine, the comparison against the MIN value will not have the desired behavior.  I am sorry about that.  I have removed the checks against the MIN value, since they are neither needed nor correct in all cases.  I will assume that this has fixed the problem.  If this is not the case, please let me know and I will re-open this issue.  See commit  fa6834f4fba8452da6d4fe1c63a378de4d3bff16 for the bug fix.

**Comment by ilovezfs** [comment]
@mdadams Thanks for the fix. The regression is gone. FYI: https://github.com/Homebrew/homebrew-core/pull/6649

**Comment by mdadams** [comment]
@ilovezfs  Thanks for confirming that the problem is resolved. :)
