### ISSUE TITLE
Corrupt jpg triggers antivirus heuristic

### ISSUE THREAD

**Issue by sparr** [mdadams/jasper#96]
`data/test/bad/1_crash.jpg` triggers the Bloodhound.Exploit.314 heuristic in Symantec Antivirus. That signature is for a code execution exploit in Windows dealing with invalid jpeg files. I suspect the reason this image is known-bad for the test suite is related to the exploit in question.

**Comment by mdadams** [comment]
Please see the last part of the discussion for issue #25.

The person who submitted the JPEG file in question generated it with a fuzzer (namely, American Fuzzy LOP).  So, it is highly unlikely that this file contains malware.  To the best of my knowledge, only Symantec Antivirus reports this file as being bad.  So, it appears that the bad result from Symantec Antivirus is a false positive.  In any case, to prevent unnecessary worrying on the part of JasPer users, I'm going to drop it from future JasPer release tarballs, and just keep it in the Git repository for JasPer  (unless, of course, Symantec fixes their software so it does not report this file as a false positive).  Otherwise, this type of bug report is likely going to keep being submitted over and over. ;)  Anyways, my current assessment is that this file poses little or no risk.  To be safe, however, don't load the file into Microsoft Paint.  Or, if you want to be extra safe, just delete the file.  It is not needed, except as a test case.

The fix that I mentioned above (i.e., to drop the file from future release tarballs) has been applied in commit d6d1638fc0b372e586ae4edf2cd3597beb3983fd.
