### ISSUE TITLE
https://bugs.gentoo.org/show_bug.cgi?id=601070

### ISSUE THREAD

**Issue by mdadams** [mdadams/jasper#97]
See:
https://bugs.gentoo.org/show_bug.cgi?id=601070

**Comment by mdadams** [comment]
@asarubbo I don't quite understand the problem.  The math library appears to be listed last on the command line for linking.  I did notice strange behavior on OSX with respect to the JPEG library previously.  I fixed this by adding the JPEG library to the link for the library.  I added the math library now as well in case this may fix things for Gentoo.  See commit 3754abcbe79fafc56f8fe7e349c2e3baf69ef540.  I am marking this issue as closed.  If the problem is not fixed, there is nothing I can do without more explanation as to what the problem is and how it is JasPer's fault, as opposed to the fault of the linker or cmake.

**Comment by jridky** [comment]
Just FYI, I had to update CMakeLists.txt to be able to build jasper-2.0.0 on Fedora. 
(see attachment for more details). Please let me know, if you find some better way than is in this patch.
[jasper-2.0.0-build-dependencies.patch.txt](https://github.com/mdadams/jasper/files/621245/jasper-2.0.0-build-dependencies.patch.txt)

**Comment by uvic-frodo** [comment]
@asarubbo and @jridky : The top-level CMakeLists.txt file should have been doing a find on the package OpenGL and adding the libraries/includes appropriately.  I have fixed this problem in commit 2e27248f9dab59b8be2dd20f5cc2e402b0e5c1a6.  I think that this should fix the Fedora build problem.  I don't think that this has anything to do with the Gentoo build problem, however, as this problem seems to be related to the math library.  Anyways, let me know if this fixes things on the Fedora side.

**Comment by jridky** [comment]
@mdadams Now It works! Thanks.

**Comment by mdadams** [comment]
@jridky Great.  Thanks for the confirmation.
