### ISSUE TITLE
Tests on ppc64 arch

### ISSUE THREAD

**Issue by jridky** [mdadams/jasper#99]
Hi,

I have tried to build and install jasper-2.0.2 on ppc64(le) architectures.
Unfortunately, I am not able to go thru run_test_3 in make test command.

It stuck at test with id prg_8. (see attachment).
I had to disable this test to be able to build it on ppc64 arch.

Please, let me know, what should I provide to you for resolve this issue.

[ppc64-test-output.txt](https://github.com/mdadams/jasper/files/624124/ppc64-test-output.txt)

**Comment by jridky** [comment]
This problem is even on ppc64le arch.
The test has not stuck only at test with id prg_8, but even at test with id prg_3.

**Comment by mdadams** [comment]
@jridky In investigating your problem, I noticed that there were a few problems with the JasPer test scripts.  First, some test cases were being run that should not be.  Also, some errors were not being correctly reported.  In fixing the first of these problems, I think that I may have fixed your problem.  There are a few test cases that are known bugs and should not be run at this time (since these bugs are not yet fixed).  The prg_8 test case is one of these known bugs.  I have disabled these tests until I have time to fix them; otherwise "make test" will fail for everyone, due to my addressing of the second problem mentioned above.  Please note that these failed test cases correspond to old JasPer bugs from prior to 1.900.1. See commit 14cc3aa91bd86ba5d349cb5032191f92f4e7045a for my changes.  Please confirm that this fixes your problem.

Incidentally, I make ask you later for further information on the prg_8 and related test cases if it would be helpful to me at that time.

**Comment by mdadams** [comment]
@jridky Since I haven't heard anything from you in a while, I am going to assume that no news is good news and this problem is resolved.  So, I am marking this issue as closed.  If you still continue to have problems, please let me know and I can re-open this issue.
